version: '3.8'
services:
  kafka:
    image: 'ghcr.io/ivishnuraj/kafka-mt5:latest'
    container_name: kafka
    restart: unless-stopped
    ports:
      - '9093:9093'
    volumes:
      - 'kafka-data:/var/lib/kafka/data'
    networks:
      - kafka-net
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - '8082:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: mt5-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: '181.215.205.67:9093'
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"mt5\" password=\"mt5-password\";\n"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: PEM
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_CERTIFICATES: | 
        -----BEGIN CERTIFICATE-----
        MIIC5jCCAc6gAwIBAgIIDPLr+mkuLpswDQYJKoZIhvcNAQELBQAwGTEXMBUGA1UE
        AxMOMTgxLjIxNS4yMDUuNjcwHhcNMjYwMzAyMjAyNDQyWhcNMzYwMjI4MjAyNDQy
        WjAZMRcwFQYDVQQDEw4xODEuMjE1LjIwNS42NzCCASIwDQYJKoZIhvcNAQEBBQAD
        ggEPADCCAQoCggEBAMBvIANCD2GtXG0vMp7QQXClkqWXmorDT5faA+pQPwJGqoq2
        Wk/YuIYYZU89jv9kNRocSN31xlUqDkYE8LVlduToyeV4moTLH7tHOZBD0rKgI46a
        Sg08ySBcaVr1hx3v7fSyGGBOijIj6UKE9uDxwLJt7tXGJkC06el72xkB5+7EzA/6
        xDkIrb3pyeYIEsGbm8cQp0T6mverqwXdg1KlpfC7QfKSEH83FfNzNqIv0UjWko+D
        /vTWOHXtSKrm7oPgsVShShR0/CgsTv2e3ccSqCuhcLrwN1RF5BQ3aaSoFgZQn8ke
        SbH95kmQ8Z0ST82il3JyD15UMy6mV+mGeK3BWz0CAwEAAaMyMDAwHQYDVR0OBBYE
        FMRlPHhwIml0itRBTE6j/fN7zJ2qMA8GA1UdEQQIMAaHBLXXzUMwDQYJKoZIhvcN
        AQELBQADggEBAErOgpiQ1W1GMCl/F7Xs/I7YIgXb/zBjpvBB/gh+Av4yDdRmJZSM
        3JywD8PriptS/n9s0WW0roistm39MX+neqM7JfOkSe9YYFPA0HhDSbr04CRtDi+o
        yE5c8MmAaG4xwZsNZs13XEnn++2K9Uwqfd8dic/K03IamwrcYC15KWaejM5xp2XK
        kgezhkboycQHnLdNgJ/AF+OacDV8JSUtnwuDM313R6tTY0nqebcd+If3qlMMrbAe
        kRjMrk7afDU3QP1ttu8BGWRXfhr80Vj193/NYS3E3Hp9PebU87ICWDlGqWb7Hz3q
        04kG7UhjZZZ7RsWRsZS27j4/jy0yTWeSfOQ=
        -----END CERTIFICATE-----
    networks:
      - kafka-net
volumes:
  kafka-data: null
networks:
  kafka-net:
    driver: bridge
