version: '3.8'
services:
  kafka:
    image: 'ghcr.io/ivishnuraj/kafka-mt5:latest'
    container_name: kafka
    restart: unless-stopped
    ports:
      - '9093:9093'
    volumes:
      - 'kafka-data:/var/lib/kafka/data'
    networks:
      - kafka-net
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - '8082:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: mt5-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: '181.215.205.67:9093'
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"mt5\" password=\"mt5-password\";\n"
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE: PEM
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_CERTIFICATES: "-----BEGIN CERTIFICATE-----\nMIIDkjCCAnqgAwIBAgIJANLrn7QaIX/2MA0GCSqGSIb3DQEBCwUAMHcxEDAOBgNV\nBAYTB1Vua25vd24xEDAOBgNVBAgTB1Vua25vd24xEDAOBgNVBAcTB1Vua25vd24x\nEDAOBgNVBAoTB1Vua25vd24xEDAOBgNVBAsTB1Vua25vd24xGzAZBgNVBAMTEnNl\ncnZlci5iYXp6YXJpby5pbjAeFw0yNjAzMDIxNjQxMDhaFw0zNjAyMjgxNjQxMDha\nMHcxEDAOBgNVBAYTB1Vua25vd24xEDAOBgNVBAgTB1Vua25vd24xEDAOBgNVBAcT\nB1Vua25vd24xEDAOBgNVBAoTB1Vua25vd24xEDAOBgNVBAsTB1Vua25vd24xGzAZ\nBgNVBAMTEnNlcnZlci5iYXp6YXJpby5pbjCCASIwDQYJKoZIhvcNAQEBBQADggEP\nADCCAQoCggEBAOq/mX66KQSlHmo/2pA91sPQBqbOW7ute/iJKd0FDEnV8Av1TAwf\nOgcTLe3bIeyYJW56w70TqpqKqEFzXfEsvg0wPUBvlYhmT29edONYbJ87LG5lgD+u\n/8PNkFaYEjE6dkYfKpyI/fey6Jii2zZi3RB3+SlMFfp7Mzqoyol0GOKobMNyMCHr\nzMEfDx4x9+D3iSdkCnFMIUHwaEprAEH3eQ7hjPZGrMws361v5s6mdEM9ctI0Gxgu\nt4N/1R9M5+tyrZyULS7A1FHf5AU1AVRZeXi8cERgtNL1nQ1D5EivvQJERhFUijxl\nBUNmuq+4zxTMihVEYfuMCJf7IbKS+VWzpVMCAwEAAaMhMB8wHQYDVR0OBBYEFNHs\nAkuvqiKVLLk0wL5jfl0GfZgZMA0GCSqGSIb3DQEBCwUAA4IBAQB1aww1etGIVrWr\nIEryFts1+kmmVqtYelms6yKj1Oy9qTFSpLETdIsz3lvcRWh7q8gAHWWB9s6DpZQ5\nnfkv3dvR9Qv7TgeQbJAV7xJgPJ5EsHNBgWhlvp57axbxptD/uDnreqso3MAFZYJH\nu65ugKRUyIWFNtrafXSdpWNgptoqapedkEJrAa6lWT6vDkPyfUQD7ZKrwtYnDSmm\nzMIs+MqN0CEw82U86AvrWsLmgFXytELKQY+Szs9a9w6l8cnfZ+DrXRuUemst3b1F\nNAq/WdbAAOuJhrGeZYfbGHaYa3CYyXOmZpugKgC8Cw9n23WypkKacaNCK3t2a1G/\n8BAtKwm6\n-----END CERTIFICATE-----\n"
    networks:
      - kafka-net
volumes:
  kafka-data: null
networks:
  kafka-net:
    driver: bridge
