version: "3.8"

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    restart: unless-stopped

    ports:
      - "9093:9093"

    volumes:
      - ./kafka-data:/var/lib/kafka/data
      - ./ssl:/etc/kafka/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
      - ./server.properties:/etc/kafka/server.properties

    command: >
      bash -c "
      if [ ! -f /var/lib/kafka/data/meta.properties ]; then
        /opt/kafka/bin/kafka-storage.sh format -t $(/opt/kafka/bin/kafka-storage.sh random-uuid) -c /etc/kafka/server.properties;
      fi &&
      /opt/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties
      "


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8082:8080"

    environment:
      KAFKA_CLUSTERS_0_NAME: mt5-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="mt5user"
        password="StrongPassword123";
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka/ssl/kafka.truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: admin@123

    volumes:
      - ./ssl:/etc/kafka/ssl